language: python
python:
  - 2.7

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt
  - docker pull dgarros/tcpreplay 
  - docker build -t juniper/open-nti .

script:
  - python -m pytest -v --durations=10
