

# lb:
#   image: jwilder/nginx-proxy
#   links:
#    - opennti-input-jti
#   volumes:
#    - /var/run/docker.sock:/tmp/docker.sock:ro
#   ports:
#    - "50000:50000/udp"
#    - "50010:50010/udp"
#    - "50020:50020/udp"

# opennti-kapacitor:
#   image: juniper/open-nti-kapacitor
#   environment:
#    - "KAPACITOR_INFLUXDB_0_URLS_0=http://opennti:8086"
#   ports:
#    - "9093:9092"
#   links:
#    - opennti

#####################################
## Message Bus and Consumers       ##
#####################################
kafka:
  image: spotify/kafka
  environment:
   - "ADVERTISED_PORT=9092"
   - "ADVERTISED_HOST=172.29.110.168"
  volumes:
   - /etc/localtime:/etc/localtime
  ports:
   - "2181:2181"
   - "9092:9092"

kafka-consumer-jti:
  image: juniper/open-nti-kafka-consumer
  environment:
    - "INFLUXDB_ADDR=opennti"
    - "KAFKA_TOPIC=jnpr.jvision"
    - "ZOOKEEPER_ADDR=172.29.110.168"
  volumes:
   - /etc/localtime:/etc/localtime
  links:
   - kafka
   - opennti

kafka-consumer-syslog:
  image: juniper/open-nti-kafka-consumer
  environment:
    - "INFLUXDB_ADDR=opennti"
    - "KAFKA_TOPIC=events"
    - "ZOOKEEPER_ADDR=172.29.110.168"
  volumes:
   - /etc/localtime:/etc/localtime
  links:
   - kafka
   - opennti

kafka-consumer-analyticsd:
  image: juniper/open-nti-kafka-consumer
  environment:
    - "INFLUXDB_ADDR=opennti"
    - "KAFKA_TOPIC=jnpr.analyticsd"
    - "ZOOKEEPER_ADDR=172.29.110.168"
  volumes:
   - /etc/localtime:/etc/localtime 
  links:
   - kafka
   - opennti

#################
## Input
#################

input-jti:
  image: juniper/open-nti-input-jti
  environment:
   - "KAFKA_ADDR=172.29.110.168"
   #- "KAFKA_TOPIC=jnpr.jvision"
   - "OUTPUT_KAFKA=true"
   - "OUTPUT_STDOUT=true"
   - "OUTPUT_INFLUXDB=false"
   - "PORT_JTI=40000"
   # - "PORT_ANALYTICSD=40020"
  ports:
   - "40000:40000/udp"
   # - "40020:40020/udp"
  expose:
   - "40000/udp"
   # - "40020/udp"
  volumes:
   - /etc/localtime:/etc/localtime
  links:
   - kafka

input-analyticsd:
  image: juniper/open-nti-input-jti
  environment:
   - "KAFKA_ADDR=172.29.110.168"
   - "KAFKA_TOPIC=jnpr.analyticsd"
   - "OUTPUT_KAFKA=true"
   - "OUTPUT_STDOUT=true"
   - "OUTPUT_INFLUXDB=false"
   # - "PORT_JTI=40000"
   - "PORT_ANALYTICSD=50020"
  ports:
   # - "40000:40000/udp"
   - "50020:50020/udp"
  expose:
   # - "40000/udp"
   - "40020/udp"
  volumes:
   - /etc/localtime:/etc/localtime
  links:
   - kafka

opennti-input-syslog:
  image: juniper/open-nti-input-syslog
  environment:
   - "KAFKA_ADDR=172.29.110.168"
   - "KAFKA_TOPIC=events"
   - "INFLUXDB_ADDR=opennti"
   - "OUTPUT_KAFKA=true"
   - "OUTPUT_STDOUT=true"
   - "OUTPUT_INFLUXDB=true"
   - "PORT_SYSLOG=6000"
  volumes:
   - /etc/localtime:/etc/localtime
  ports:
   - "6000:6000/udp"
  expose:
   - "6000/udp"
  links:
   - kafka
   - opennti

#################
## Open NTI - Database / Gui
#################
opennti:
  image: juniper/open-nti:grafana3_0_influxdb_0_13
  restart: always
  volumes:
   - ./dashboards:/src/dashboards
   - ./dashboards:/opt/open-nti/data
   - /etc/localtime:/etc/localtime
  ports:
   - "8125:8125/udp"
   - "80:80"
   - "3000:3000"
   - "8083:8083"
   - "8086:8086"
